# Inspired by https://github.com/zopefoundation/Zope/blob/master/.github/workflows/tests.yml
name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 12 * * 0'  # run once a week on Sunday
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      # We want to see all failures:
      fail-fast: false
      matrix:
        os:
        - linux
        config:
        - "3.6" # For CentOS 7 deployments
        - "3.7"
        - "3.8"
        - "3.9"
        - "3.10"
        # - "3.11" # not yet released
    runs-on: ${{ matrix.os }}-latest
    name: ${{ matrix.os }}-${{ matrix.config }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config }}
    - name: Pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.config }}-${{ hashFiles('setup.*', 'requirements*') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.config }}-
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip zope-testrunner
        pip install -e .
    - name: Test
      run: zope-testrunner -pvc --test-path=. 
